### PR TITLE
Issue with scoped package #2

### PR DESCRIPTION
**Pull request by bn3t**
This is my attempt to fix the problem described in Issue #2.  It has been discussed on Discord with @malept.

### CODE REVIEW

**Comment by bn3t** [comment]
Hi @timfish, would you consider merging this and making a release on npm?

**Comment by timfish** [comment]
Sorry it's taken me so long to respond, I've had an extremely busy couple of months and now I'm away for a while.

I'm reluctant to publish any changes without a proper test suite in place especially as I don't fully understand the source of the issue and any further implications.

If you convert your forge config to JavaScript, you can include custom plugin code inline which means you can use your modified code without me publishing everything. I'll see if I can remote desktop into my office machine and get an example of how to do this.

**Comment by timfish** [comment]
To include custom plugin in forge JavaScript config...

In your `package.json`:
```json
  "config": {
    "forge": "./forge.config.js"
  },
```
In `forge.config.js`:
```ts
const { Walker, DepType } = require("flora-colossus");
const { dirname } = require("path");

module.exports = {
  packagerConfig: {},
  makers: [ ],
  plugins: [
    [
      "@electron-forge/plugin-webpack",
      {
        mainConfig: "./webpack.main.config.js",
        renderer: {
          config: "./webpack.renderer.config.js",
          entryPoints: [
            {
              html: "./src/index.html",
              js: "./src/renderer.ts",
              name: "main_window",
            },
          ],
        },
      },
    ],
    {
      __isElectronForgePlugin: true,
      async init() {
        // nothing here
      },
      getHook(hookName) {
        switch (hookName) {
          case "resolveForgeConfig":
            return this.resolveForgeConfig;
        }
      },
      async resolveForgeConfig(forgeConfig) {
        // Code from plugin here which modifies config
        return forgeConfig;
      },
    },
  ],
};
```

**Comment by silveiralsv** [comment]
@bn3t  since file also include subfolders and file extension, this change won't work. 

Eg:
```
 foundModules = ['@serialport/parser-slip-encoder']
file = '/node_modules/@serialport/parser-slip-encoder/dist/package.json'
```


@timfish & @bn3t  please check and merge this one instead: 
[PR](https://github.com/timfish/forge-externals-plugin/pull/5)

**Comment by timfish** [comment]
I found some time and ended up merging #7 and releasing v0.2

**Pull request closed without merging**
